### ISSUE TITLE
Copy/Paste breaks the editor

### ISSUE THREAD

**Issue by giohappy** [docb/dbRackFormulaOne#5]
VCV Rack 2 on Windows 11.
When I paste any example, the editor introduces chars which break the editor. The cursor goes mad and editing becomes impossible until I select all the delete.

The same happens if I write from the beginning in the editor -> select all -> copy -> paste -> boom, this is what I get:

![image](https://github.com/docb/dbRackFormulaOne/assets/571129/7d7521af-4b57-4560-b64a-6a5680a05279)

and if I select all you can see that the selection is also gone crazy:

![image](https://github.com/docb/dbRackFormulaOne/assets/571129/8f3261ae-b624-4103-add9-9988e6ed6e68)

I suspect this is an encoding problem with `std:string` and `UTF-8 `

**Comment by giohappy** [comment]
A workaround is to use the [Fermata](https://library.vcvrack.com/?brand=Stochastic%20Telegraph) module as an intermediate step for pasting code, because copy/paste from Fermata to FormulaOne  works.

**Comment by docb** [comment]
Hi thanks for your report. I think the browser adds these chars and the editor does currently not filter out any char on paste.
But this can be done in the next version. Which browser do you use?

**Comment by giohappy** [comment]
@docb I don't think it depends on the browser. It also happens if I type the code in the Windows Notepad. 
It looks like the issue is the carriage return (`U+000D`) that Windows adds after Line Fieed (`U+000A`)

Example that isn't pasted correctly:

```
var v := 0;
if (a>0) {
 v := 1;
}
else {
 v := 0;
}
var out := v;
```

This is what I get when I write and copy the text from FormuilaOne:

```
76 61 72 20 76 20 3A 3D 20 30 3B 0A 69 66 20 28 
61 3E 30 29 20 7B 0A 20 76 20 3A 3D 20 31 3B 0A 
7D 0A 65 6C 73 65 20 7B 0A 20 76 20 3A 3D 20 30 
3B 0A 7D 0A 76 61 72 20 6F 75 74 20 3A 3D 20 76 
3B
```

and this is what I when I write and copy the text from Notepad:

```
76 61 72 20 76 20 3A 3D 20 30 3B 0D 0A 69 66 20 
28 61 3E 30 29 20 7B 0D 0A 20 76 20 3A 3D 20 31 
3B 0D 0A 7D 0D 0A 65 6C 73 65 20 7B 0D 0A 20 76 
20 3A 3D 20 30 3B 0D 0A 7D 0D 0A 76 61 72 20 6F 
75 74 20 3A 3D 20 76 3B
```

Notice the extra `U+000D`:

76 61 72 20 76 20 3A 3D 20 30 3B **0D** 0A 69 66 20

**Comment by docb** [comment]
Ok this was never a problem before some time. 
And now I have tested this behavior with the standard Notes module of the VCV Rack Fundamentals:
same issue. 

I will check this and may asking the VCV Rack developers.

**Comment by giohappy** [comment]
I confirm the same issue with Notes, while [Fermata](https://library.vcvrack.com/?brand=Stochastic%20Telegraph) works fine

**Comment by docb** [comment]
@giohappy  should be ok now in this release  https://github.com/docb/dbRackFormulaOne/releases/tag/v2.0.2

**Comment by giohappy** [comment]
Thx @docb. I'll give it a try asap. I will also explore the new features.

**Comment by giohappy** [comment]
I confirm it was perfectly now. Thanks again.

**Comment by docb** [comment]
@giohappy  Thank you for reporting and confirming.
